# 2020-6-29

language: python

python:
    - "3.6"
    - "3.7"

before_install:
    - python --version
    - pip install -U pip

install:
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Add all project dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda install -c conda-forge numpy
  - conda install -c conda-forge pandas
  - conda install rpy2
  - conda install r-essentials r-base
  - conda install pytest # Use this for testing

  # Install R packages with conda
  - sudo wget https://cran.r-project.org/src/contrib/NbClust_3.0.tar.gz
  - R CMD INSTALL NbClust_3.0.tar.gz

script:
    # Dont be ambiguous about where your test files are at
    - pytest ./c_index/c_index_test.py # Run tests
    - pytest ./c_index/c_index_R_interface_test.py

